version: '3'
services:
  selenoid:
    image: "aerokube/selenoid"
    network_mode: bridge
    ports:
      - "4444:4444"
    volumes:
      - "/c/Users/Vladyslav_Tovkun/selenoid/config:/etc/selenoid"
      - "/c/Users/Vladyslav_Tovkun/selenoid/video:/opt/selenoid/video"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: ["-video-output-dir", "/c/Users/Vladyslav_Tovkun/selenoid/video"]
  selenoid-ui:
    image: "aerokube/selenoid-ui"
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]